import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('real activity candidates', () => {
  it('loads each profile once when it selected any detailed interest in the chosen activity filters', () => {
    const api = read('server/api/activities/people.get.ts')
    expect(api).toContain('array_agg(coalesce(a.name,pa.custom_label)')
    expect(api).toContain('a.category=any($1::text[])')
    expect(api).toContain('pa.custom_category=any($1::text[])')
    expect(api).toContain('$3::boolean and pa.custom_label is not null')
    expect(api).toContain("effectiveSlugs.includes('your-ideas')")
    expect(api).toContain('all_selected."allActivityTags"')
    expect(api).toContain('shared_exact."sharedActivityTags"')
    expect(api).toContain('matchedActivityTags: matchedActivityTags.filter')
    expect(api).toContain('otherActivityTags: otherActivityTags.slice(0, 3)')
    expect(api).toContain('p.user_id<>$2')
    expect(api).toContain('recipientInterestAvailabilitySelect')
    expect(api).not.toContain('recipientInterestAvailabilityWhere')
    expect(api).toContain("m.status in ('active','queued')")
    expect(api).toContain('order by coalesce(cardinality(shared_exact."sharedActivityTags"),0) desc')
    const page = read('pages/activities/index.vue')
    expect(page).toContain('databasePeople.value')
    expect(page).toContain(":aria-label=\"`View ${person.name}'s profile`\"")
    expect(page).toContain(':key="person.slug"')
    expect(page).not.toContain('showInterest(person.slug, person.name)')
    expect(page).not.toContain('useDailyInterest()')
    expect(page).toContain('Everyone appears once')
    expect(page).toContain('Choose one or more broad categories')
    expect(page).toContain('Based on my activities')
    expect(page).toContain('categories from activities saved to your profile')
    expect(page).toContain('Using your saved activity categories')
    expect(page).not.toContain('All for you')
    expect(page).not.toContain('Based on your saved interests')
    expect(page).toContain('person.sharedActivityTags')
    expect(page).toContain('person.matchedActivityTags')
    expect(page).toContain('You both enjoy')
    expect(page).toContain('Matches your activity filters')
    expect(page).not.toContain('Considering other interests')
    expect(page).toContain('appliedFilters.orientationLabel')
    expect(page).toContain("appliedFilters.racialPreferencesApplied ? 'Ethnicity filter active' : 'All ethnicities'")
    expect(page).not.toContain('selected</span>')
    expect(page).not.toContain('{{ person.detail }}')
    expect(page).not.toContain('person.distanceKm')
    expect(page).toContain('Load more people')
    expect(api).toContain('racialPreferencesApplied')
    expect(page).toContain('Applied match preferences')
    expect(page).toContain('Ages {{ appliedFilters.minimumAge }}–{{ appliedFilters.maximumAge }}')
    expect(page).toContain('Within {{ appliedFilters.distance }} km')
    expect(page).toContain('Using ${appliedFilters.searchLocation}')
    expect(api).toContain('p.postcode_area as "postcodeArea"')
    expect(page).toContain('{{ person.place }}')
    expect(page).toContain('Nobody here fits these filters yet')
    expect(page).toContain('Fine-tune matches')
  })

  it('supports wellness, nightlife, exploration and community discovery', () => {
    const discovery = read('utils/activityDiscovery.ts')
    const activities = read('pages/activities/index.vue')
    const preferences = read('pages/preferences/activities.vue')
    for (const category of ['Wellness','Nightlife','Explore','Community']) {
      expect(discovery).toContain(`name: '${category}'`)
      expect(activities).toContain(`name: '${category}'`)
      expect(preferences).toContain(`name: '${category}'`)
    }
    expect(read('docs/migrations/20260811_add_activity_discovery_categories.sql')).toContain("('Wellness','Yoga')")
    const refinedIdeas = read('docs/migrations/20260826_refine_activity_date_ideas.sql')
    for (const activity of ['Restaurants', 'Pilates classes', 'Tai chi', 'Sound baths', 'Walking tours', 'Community gardening']) {
      expect(preferences).toContain(`'${activity}'`)
      expect(refinedIdeas).toContain(`'${activity}'`)
    }
  })

  it('separates food and drink from activities members wrote themselves', () => {
    const discovery = read('utils/activityDiscovery.ts')
    const activities = read('pages/activities/index.vue')

    expect(discovery).toContain("'food-drink': { name: 'Food & drink', databaseCategories: ['Food and drink'] }")
    expect(discovery).toContain("'your-ideas': { name: 'Your ideas', databaseCategories: [], customOnly: true }")
    expect(discovery).toContain("casual: 'food-drink'")
    expect(activities).toContain("slug: 'your-ideas', name: 'Your ideas'")
    expect(activities).not.toContain("name: 'Casual'")
  })
})
