import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('sexual orientation and profile weight', () => {
  it('stores and filters sexual orientation separately from gender', () => {
    const migration = read('docs/migrations/20260823_add_sexual_orientation_preferences.sql')
    const preferences = read('server/api/preferences/dating.put.ts')
    const discovery = read('server/utils/discoveryFilters.ts')
    expect(migration).toContain('sexual_orientation')
    expect(migration).toContain('interested_orientations')
    expect(preferences).toContain('no_orientation_preference')
    expect(preferences).toContain('Choose at least one sexual orientation you are open to dating')
    expect(read('pages/onboarding.vue')).not.toContain('sexualOrientationPreferenceOptions')
    expect(read('pages/preferences/dating.vue')).toContain('!preferences.orientations.length')
    expect(discovery).toContain('p.sexual_orientation=any(mine.interested_orientations)')
    expect(discovery).toContain('viewer.sexual_orientation=any(theirs.interested_orientations)')
  })

  it('allows an optional weight next to height and displays it on profiles', () => {
    const migration = read('docs/migrations/20260824_add_profile_weight.sql')
    const lifestyle = read('server/api/profile/lifestyle.put.ts')
    const details = read('pages/profile/details.vue')
    const profile = read('pages/profiles/[slug].vue')
    expect(migration).toContain('weight_kg')
    expect(lifestyle).toContain('weight_kg=$3')
    expect(details).toContain('v-model.number="lifestyle.weightKg"')
    expect(details).toContain('min="35" max="300"')
    expect(profile).toContain('profileDetails(profile.value)')
    expect(profile.indexOf('<ProfileSafetyActions')).toBeLessThan(profile.indexOf('v-if="lifestyleDetails.length"'))
    expect(profile).toContain("bioNeedsExpansion && !bioExpanded && 'line-clamp-6'")
    expect(profile).toContain('Read more')
    expect(profile).toContain('lg:items-start')
    expect(profile).not.toContain('lg:sticky lg:top-24')
    expect(profile).toContain('profileDetailsCollapsed')
    expect(profile).toContain('aria-controls="viewed-profile-details"')
    expect(profile).toContain('id="viewed-profile-details" v-show="!profileDetailsCollapsed"')
    expect(profile).toContain('contents lg:flex lg:flex-col lg:gap-5')
    expect(profile).toContain('profile-summary-flip order-2 min-w-0 max-w-full')
    expect(profile).toContain("profileCardFlipped && 'is-flipped'")
    expect(profile).toContain(':inert="profileCardFlipped || undefined"')
    expect(profile).toContain(':inert="!profileCardFlipped || undefined"')
    expect(profile).toContain('profile-summary-back')
    expect(profile).toContain('flex flex-wrap items-start justify-between gap-3')
    expect(profile).toContain('aria-label="View About me"')
    expect(read('utils/profileDetails.ts')).toContain("label: 'Weight'")
    expect(read('utils/profileDetails.ts')).toContain('Flexible — mornings or evenings')
  })
})
