import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('matches and date planning dashboard', () => {
  it('groups persisted matches by their next action', () => {
    const page = read('pages/matches/index.vue')
    expect(page).toContain("'/api/matches'")
    expect(page).toContain("return 'Start planning'")
    expect(page).toContain("return 'Edit date details'")
    expect(page).toContain("'Review proposal'")
    expect(page).toContain("'Edit proposal'")
    expect(page).toContain('Draft — only you can see this')
    expect(read('server/api/matches/index.get.ts')).toContain("proposalStatus === 'accepted' ? 'confirmed'")
  })

  it('allows a proposal to be confirmed and material details to be edited', () => {
    expect(read('server/api/proposals/[id]/respond.post.ts')).toContain("['accepted', 'declined']")
    expect(read('server/api/proposals/[id].put.ts')).toContain("senderEditingDraft ? 'draft' : 'pending'")
    expect(read('pages/plans/[slug].vue')).toContain('Save as draft')
    expect(read('pages/plans/[slug].vue')).toContain('Confirm and send')
    expect(read('pages/plans/[slug].vue')).toContain("await navigateTo('/matches')")
    expect(read('pages/plans/[slug].vue')).toContain("respond('accepted', times[0]?.id)")
    expect(read('pages/plans/[slug].vue')).toContain('Accept proposal')
    expect(read('pages/plans/[slug].vue')).not.toContain('Accept one of their times')
    expect(read('pages/plans/[slug].vue')).toContain('Suggest a completely different date')
    expect(read('pages/plans/[slug].vue')).toContain('Send new proposal')
    expect(read('server/api/proposals/[id].put.ts')).toContain('recipientReproposing')
    expect(read('server/api/proposals/index.post.ts')).toContain("'Proposed time', 1")
    expect(read('pages/plans/[slug].vue')).toContain('Send suggested changes')
    expect(read('pages/plans/[slug].vue')).toContain('type="datetime-local"')
    expect(read('pages/plans/[slug].vue')).toContain(':min="earliestCustomTime"')
    expect(read('pages/plans/[slug].vue')).toContain('Selected: {{ chosenCustomTimeLabel }}')
    expect(read('pages/plans/[slug].vue')).toContain('4. Enter a public venue')
    expect(read('server/api/proposals/[id].put.ts')).toContain("current.status === 'pending'")
    expect(read('server/api/proposals/index.post.ts')).toContain("'draft'")
    expect(read('server/api/proposals/index.post.ts')).not.toContain("'proposal_received'")
    expect(read('server/api/proposals/[id]/send.post.ts')).toContain("'proposal_received'")
    expect(read('server/api/planning/[slug].get.ts')).toContain("dp.status<>'draft' or dp.inviter_id=$1")
  })

  it('shows at most five matches and confirms removal before notifying the other person', () => {
    expect(read('server/api/matches/index.get.ts')).toContain('limit 5')
    expect(read('pages/matches/index.vue')).toContain('You have {{ additionalMatches }} more')
    expect(read('pages/matches/index.vue')).toContain('v-if="showSummaryCounts" class="mt-3 grid')
    expect(read('pages/matches/index.vue')).toContain('<strong>{{ totalMatches }}</strong>')
    expect(read('pages/matches/index.vue')).toContain('<strong>{{ interestReceivedCount }}</strong>')
    expect(read('pages/matches/index.vue')).toContain("showSummaryCounts ? 'Hide counts' : 'Show counts'")
    expect(read('pages/matches/index.vue')).toContain('EyeOff v-if="showSummaryCounts"')
    expect(read('server/api/matches/index.get.ts')).toContain('count(distinct di.sender_id)::int as count')
    expect(read('pages/matches/index.vue')).toContain('Your plan allows up to {{ activeMatchLimit }} active matches')
    expect(read('pages/matches/index.vue')).toContain('class="summary-icon"')
    expect(read('pages/matches/index.vue')).toContain('summary-confirmed')
    expect(read('components/BlankNavBar.vue')).toContain('matchCount')
    expect(read('server/api/navigation/counts.get.ts')).toContain("status='active'")
    const migration = read('docs/migrations/20260722_enforce_five_active_matches.sql')
    expect(migration).toContain('matches_enforce_five_active')
    expect(migration).toContain('pg_advisory_xact_lock')
    const planAwareMigration = read('docs/migrations/20260812_plan_aware_active_match_limit.sql')
    expect(planAwareMigration).toContain("then 5")
    expect(planAwareMigration).toContain("else 3")
    expect(planAwareMigration).toContain('matches_enforce_active_limit')
    expect(read('pages/matches/index.vue')).toContain('Yes, remove match')
    const remove = read('server/api/matches/[id].delete.ts')
    expect(remove).toContain("set status='unmatched'")
    expect(remove).toContain("'match_ended'")
  })
})
