import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('matches and date planning dashboard', () => {
  it('groups persisted matches by their next action', () => {
    const page = read('pages/matches/index.vue')
    expect(page).toContain("'/api/matches?includeNotifications=true'")
    expect(page).toContain("return 'Start planning'")
    expect(page).toContain("return 'View date plan'")
    expect(page).toContain("return 'View reschedule'")
    expect(page).toContain("'Review proposal'")
    expect(page).toContain("'Edit proposal'")
    expect(page).toContain("return 'Plan another date'")
    expect(page).toContain("return 'See if you can start'")
    expect(page).toContain("title: 'Reply to a plan'")
    expect(page).toContain("title: 'Make a plan'")
    expect(page).toContain("title: 'After your date'")
    expect(page).toContain("title: 'Upcoming dates'")
    expect(page).toContain("`/plans/${match.slug}?new=1`")
    expect(page).toContain('Draft — only you can see this')
    const matchesApi = read('server/api/matches/index.get.ts')
    expect(matchesApi).toContain("proposalStatus === 'accepted' ? 'confirmed'")
    expect(matchesApi).toContain("row.status === 'queued' ? 'queued'")
  })

  it('allows a proposal to be confirmed and pending details to be revised', () => {
    expect(read('server/api/proposals/[id]/respond.post.ts')).toContain("['accepted', 'declined']")
    expect(read('server/api/proposals/[id].put.ts')).toContain("senderEditingDraft ? 'draft' : 'pending'")
    expect(read('pages/plans/[slug].vue')).toContain('Save as draft')
    expect(read('pages/plans/[slug].vue')).toContain('Confirm and send')
    expect(read('pages/plans/[slug].vue')).toContain("await navigateTo('/matches')")
    expect(read('pages/plans/[slug].vue')).toContain('Here is exactly what you sent them.')
    expect(read('pages/plans/[slug].vue')).toContain('Your proposed date')
    expect(read('pages/plans/[slug].vue')).toContain('Awaiting reply')
    expect(read('pages/plans/[slug].vue')).toContain('aria-labelledby="sent-proposal-title"')
    expect(read('pages/plans/[slug].vue')).toContain('Your note')
    expect(read('pages/plans/[slug].vue')).toContain("respond('accepted', times[0]?.id)")
    expect(read('pages/plans/[slug].vue')).toContain('Accept proposal')
    expect(read('pages/plans/[slug].vue')).not.toContain('Accept one of their times')
    expect(read('pages/plans/[slug].vue')).toContain('Suggest a different plan')
    expect(read('pages/plans/[slug].vue')).toContain('Send new proposal')
    expect(read('server/api/proposals/[id].put.ts')).toContain('recipientReproposing')
    expect(read('server/api/proposals/index.post.ts')).toContain("'Proposed time', 1")
    expect(read('pages/plans/[slug].vue')).toContain('Send suggested changes')
    expect(read('pages/plans/[slug].vue')).toContain('Short reply')
    expect(read('server/api/proposals/[id].put.ts')).toContain('recipientSuggestingChange')
    expect(read('pages/plans/[slug].vue')).toContain('type="datetime-local"')
    expect(read('pages/plans/[slug].vue')).toContain(':min="earliestCustomTime"')
    expect(read('pages/plans/[slug].vue')).toContain('Selected: {{ chosenCustomTimeLabel }}')
    expect(read('pages/plans/[slug].vue')).toContain('4. Choose where to meet')
    expect(read('server/api/proposals/[id].put.ts')).toContain("current.status === 'pending'")
    expect(read('server/api/proposals/index.post.ts')).toContain("'draft'")
    expect(read('server/api/proposals/index.post.ts')).not.toContain("'proposal_received'")
    expect(read('server/api/proposals/[id]/send.post.ts')).toContain("'proposal_received'")
    expect(read('server/api/planning/[slug].get.ts')).toContain("dp.status<>'draft' or dp.inviter_id=$1")
    expect(read('pages/plans/[slug].vue')).toContain("route.query.new !== '1'")
  })

  it('suggests and enforces times within both members’ usual availability', () => {
    const page = read('pages/plans/[slug].vue')
    const availabilityGuard = read('server/utils/proposalAvailability.ts')
    expect(page).toContain('fitsSharedAvailability')
    expect(page).toContain('with at least an hour free')
    expect(page).toContain('3. Suggest a date and time')
    expect(page).toContain('Times that fit both schedules')
    expect(page).toContain('chooseSuggestedTime(option)')
    expect(page).not.toContain('v-for="time in times"')
    expect(read('server/api/planning/[slug].get.ts')).toContain('suggestedTimes')
    expect(read('server/api/proposals/index.post.ts')).toContain('ensureTimesFitSharedAvailability')
    expect(read('server/api/proposals/[id].put.ts')).toContain('ensureTimesFitSharedAvailability')
    expect(availabilityGuard).toContain('Choose a time that fits both of your usual schedules')
    expect(availabilityGuard).toContain('672 constant-time checks')
    expect(availabilityGuard).toContain("a.end_time-(chosen.proposed_at at time zone")
  })

  it('shows connections by their next human action and explains capacity only when full', () => {
    expect(read('server/api/matches/index.get.ts')).toContain('limit 25')
    expect(read('pages/matches/index.vue')).toContain('You have {{ additionalMatches }} more')
    expect(read('pages/matches/index.vue')).toContain("title: 'Waiting to start'")
    expect(read('pages/matches/index.vue')).toContain('activateQueuedMatch(match)')
    expect(read('pages/matches/index.vue')).toContain('v-if="interestReceivedCount"')
    expect(read('pages/matches/index.vue')).toContain('v-if="connectionListFull"')
    expect(read('pages/matches/index.vue')).toContain('One new connection needs your attention')
    expect(read('pages/matches/index.vue')).not.toContain('Manual matches')
    expect(read('pages/matches/index.vue')).not.toContain('showSummaryCounts')
    const matchesEndpoint = read('server/api/matches/index.get.ts')
    expect(matchesEndpoint).toContain('with member_matches as materialized')
    expect(matchesEndpoint).toContain('from summary cross join settings')
    expect(matchesEndpoint).toContain('interest_inbox_state')
    expect(matchesEndpoint).not.toContain('count(distinct di.sender_id)::int as count')
    expect(matchesEndpoint.match(/database\.query/g)).toHaveLength(1)
    expect(matchesEndpoint).toContain('listNotifications(database, sub)')
    expect(read('pages/matches/index.vue')).toContain("journeySection(match) === section.key")
    expect(read('pages/matches/index.vue')).toContain('Connections Dashboard Viewed')
    expect(read('pages/matches/index.vue').indexOf('v-for="section in sections"')).toBeLessThan(
      read('pages/matches/index.vue').indexOf('aria-labelledby="match-updates-title"'),
    )
    expect(read('components/BlankNavBar.vue')).toContain('matchCount')
    expect(read('server/api/navigation/counts.get.ts')).toContain("status in ('active','queued')")
    const migration = read('docs/migrations/20260722_enforce_five_active_matches.sql')
    expect(migration).toContain('matches_enforce_five_active')
    expect(migration).toContain('pg_advisory_xact_lock')
    const equalLimitMigration = read('docs/migrations/20260913_remove_consumer_limit_paywalls.sql')
    expect(equalLimitMigration).toContain('>= 5')
    expect(equalLimitMigration).not.toContain('entitlements')
    expect(equalLimitMigration).toContain('enforce_active_match_limit')
    expect(read('pages/matches/index.vue')).toContain('Yes, close connection')
    const remove = read('server/api/matches/[id].delete.ts')
    expect(remove).toContain("set status='unmatched'")
    expect(remove).toContain('delete from date_proposals where match_id=$1')
    expect(remove).toContain("'match_ended'")
  })
})
