import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('first-login onboarding', () => {
  it('redirects incomplete authenticated users into a resumable flow', () => {
    expect(read('server/api/auth/callback.get.ts')).toContain('/onboarding?redirect=')
    expect(read('middleware/logged-in.ts')).toContain('/api/onboarding/status')
    expect(read('pages/onboarding.vue')).toContain("step.value = status.nextStep")
  })

  it('persists every onboarding stage before completion', () => {
    const page = read('pages/onboarding.vue')
    expect(page).toContain("'/api/account/v2/profile'")
    expect(page).toContain("'/api/profile/me'")
    expect(page).toContain("'/api/preferences/activities'")
    expect(page).toContain("'/api/preferences/general'")
    expect(page).toContain("'/api/preferences/dating'")
    expect(page).toContain("'/api/onboarding/complete'")
    expect(page).not.toContain('Profile URL')
    expect(page).toContain('You can update your profile, activities, preferences and photos later')
    expect(page).toContain('profile.slug ||= createProfileSlug()')
    expect(page).toContain("'/api/profile/name-availability'")
    expect(page).toContain('That name is already in use')
    expect(page).toContain('v-model="birthDate.day"')
    expect(page).toContain('v-model="birthDate.month"')
    expect(page).toContain('v-model="birthDate.year"')
    expect(page).toContain('v-model="profile.genderIdentity"')
    expect(page.indexOf('How do you identify?')).toBeLessThan(page.indexOf('Pronouns <input v-model="profile.pronouns"'))
    expect(page).toContain('Neither / another identity')
    expect(page).toContain("name: 'Food and drink'")
    expect(page).toContain("group.name === 'Learning' ? Brain")
    expect(page).toContain('customActivityCount(group.name)')
    expect(page).toContain('Each choice helps people find you through the broader categories')
    expect(page).toContain('activities: selectedActivities.value')
    expect(page).not.toContain('When are you usually free?')
    expect(page).toContain('v-for="day in availabilityDays"')
    expect(page).toContain('v-model="day.startTime"')
    expect(page).toContain('v-model="day.endTime"')
    expect(page).toContain("'/api/preferences/schedule'")
    expect(page).not.toContain('I’m open to everyone')
    expect(page).toContain('class="meeting-preferences"')
    expect(page).toContain('Choose at least one type of person')
    expect(page).toContain('Skip photos and finish')
    expect(page).toContain('{{ step }} of 6')
    expect(page).toContain('saveRacialIdentity')
    expect(page).toContain('How do you racially or ethnically identify?')
    expect(page).toContain("profile.raceEthnicity === option")
    expect(read('docs/migrations/20260731_add_racial_identity.sql')).toContain('race_ethnicity')
    expect(page).toContain('saveDatingPreferences')
    expect(page).toContain('Racial and ethnic preferences')
    expect(page).toContain('No racial or ethnic preference')
    expect(page).toContain("'Middle Eastern', 'North African'")
    expect(page).toContain("const genderOptions = ['Women', 'Men', 'Non-binary']")
    expect(page).toContain('<span>Everyone</span>')
    expect(page).toContain('toggleGenderPreference(option)')
    expect(read('server/api/onboarding/status.get.ts')).toContain('datingComplete')
    expect(read('server/api/preferences/dating.put.ts')).toContain('dating_preferences_set=true')
    expect(read('server/api/onboarding/complete.post.ts')).not.toContain('profile_photos pp')
    expect(read('server/api/profile/me.put.ts')).toContain('gender_identity')
    expect(read('docs/migrations/20260730_add_gender_identity.sql')).toContain('profiles_gender_identity_check')
    expect(read('server/api/profile/me.put.ts')).toContain('profiles_display_name_unique')
    expect(read('docs/migrations/20260729_unique_profile_names.sql')).toContain('lower(trim(display_name))')
    expect(read('server/api/onboarding/complete.post.ts')).toContain('Please finish every onboarding step')
  })
})
