import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('first-login onboarding', () => {
  it('redirects incomplete authenticated users into a resumable flow', () => {
    expect(read('server/api/auth/callback.get.ts')).toContain('/onboarding?redirect=')
    expect(read('middleware/logged-in.ts')).toContain('onboardingComplete.value')
    expect(read('middleware/logged-in.ts')).not.toContain('/api/onboarding/status')
    expect(read('server/api/bootstrap.get.ts')).toContain('as "onboardingComplete"')
    expect(read('pages/onboarding.vue')).toContain("$fetch<OnboardingBootstrapResponse>('/api/onboarding/bootstrap')")
    expect(read('pages/onboarding.vue')).toContain("step.value = status.nextStep")
    expect(read('pages/onboarding.vue')).toContain('watch(step')
    expect(read('pages/onboarding.vue')).toContain('setOnboardingComplete()')
    expect(read('pages/onboarding.vue')).toContain("window.scrollTo({ top: 0, left: 0, behavior: 'auto' })")
  })

  it('keeps first-login setup to three progressive stages', () => {
    const page = read('pages/onboarding.vue')
    expect(page).toContain("'/api/account/v2/profile'")
    expect(page).toContain("'/api/profile/me'")
    expect(page).toContain("'/api/preferences/activities'")
    expect(page).toContain("'/api/onboarding/complete'")
    expect(page).not.toContain("'/api/preferences/general'")
    expect(page).not.toContain("'/api/preferences/dating'")
    expect(page).not.toContain("'/api/preferences/schedule'")
    expect(page).toContain('{{ step }} of 3')
    expect(page).toContain('v-for="number in 3"')
    expect(page).toContain('Age, distance, dating, lifestyle and schedule filters remain available later')
    expect(page).toContain('profile.slug ||= createProfileSlug()')
    expect(page).toContain("'/api/profile/name-availability'")
    expect(page).toContain('That name is already in use')
    expect(page).toContain('v-model="birthDate.day"')
    expect(page).toContain('v-model="birthDate.month"')
    expect(page).toContain('v-model="birthDate.year"')
    expect(page).toContain('v-model="profile.genderIdentity"')
    expect(page).toContain('v-model="profile.sexualOrientation"')
    expect(page).not.toContain('sexualOrientationPreferenceOptions')
    expect(page).not.toContain('openRaceEthnicityPreferenceLabel')
    expect(page).toContain('genderIdentityOptions')
    expect(read('utils/genderIdentity.ts')).toContain('Non-binary / another identity')

    expect(page).toContain('Where should we look?')
    expect(page).toContain(':required="!onboardingLocation.hasLocation"')
    expect(page).not.toContain('v-model.number="preferences.distance"')
    expect(page).not.toContain('v-for="day in availabilityDays"')

    expect(page).toContain("name: 'Food and drink'")
    expect(page).toContain('activityGroupIcons[group.name] || Sparkles')
    expect(page).toContain(':aria-expanded="openActivityGroups.has(group.name)"')
    expect(page).toContain('@click="toggleActivityGroup(group.name)"')
    expect(page).toContain('selectedActivityCount(group.name)')
    expect(page).toContain("'Restaurants'")
    expect(page).toContain("'Pilates classes'")
    expect(page).toContain("'Tai chi'")
    expect(page).toContain("'Sound baths'")
    expect(page).toContain("'Walking tours'")
    expect(page).toContain("'Community gardening'")
    for (const genre of ['Action & adventure games', 'Role-playing games (RPGs)', 'Shooter games',
      'Strategy games', 'Simulation & management games', 'Cosy & indie games']) {
      expect(page).toContain(`'${genre}'`)
      expect(read('pages/preferences/activities.vue')).toContain(`'${genre}'`)
      expect(read('docs/migrations/20260828_refine_gaming_categories.sql')).toContain(`('${genre}')`)
    }
    expect(page).not.toContain("'Board games'")
    expect(read('pages/preferences/activities.vue')).not.toContain("'Puzzle rooms'")
    expect(page).not.toContain("'Supper clubs'")
    expect(page).not.toContain("'Wellness classes'")
    expect(page).not.toContain("'Relaxed movement'")
    expect(page).not.toContain("'Self-care activities'")
    expect(page).not.toContain("'Neighbourhood wandering'")
    expect(page).toContain("name: 'Wellness'")
    expect(page).toContain("name: 'Nightlife'")
    expect(page).toContain("name: 'Explore'")
    expect(page).toContain("name: 'Community'")
    expect(page).toContain('function customActivityCount(category: string)')
    expect(page).toContain('activities: selectedActivities.value')
    expect(page).toContain('async function openPhotoSetup()')
    expect(page).toContain("router.push('/photos?onboarding=1')")
    expect(page).toContain('const minimumOnboardingActivities = 3')
    expect(page).toContain('const onboardingActivityLimit = 3')
    expect(page).toContain('photoCount.value >= 1')
    expect(page).toContain('saving || !setupReady')
    expect(page).not.toContain('Skip for now and finish')
    expect(page).toContain('Finish and discover people')
    expect(page).toContain('By finishing setup, you agree to our')
    expect(page).toContain('to="/terms-of-service"')
    expect(page).toContain('to="/acceptable-use"')
    expect(read('components/BlankNavBar.vue')).not.toContain('By creating an account, you agree to our')
    expect(read('pages/please-sign-in.vue')).not.toContain('By creating an account, you agree to our')
    expect(read('pages/preferences/dating.vue')).toContain('Racial and ethnic preferences')
    expect(read('pages/preferences/dating.vue')).toContain('Sexual orientation preferences')
    expect(read('server/api/preferences/dating.put.ts')).toContain('dating_preferences_set=true')
    expect(read('server/api/onboarding/complete.post.ts')).toContain('profile_photos pp')
    expect(read('server/api/onboarding/complete.post.ts')).toContain('profile_activities pa')
    expect(read('server/api/onboarding/complete.post.ts')).not.toContain('dating_preferences_set=true')
    expect(read('server/api/onboarding/complete.post.ts')).not.toContain('p.race_ethnicity is not null')
    expect(read('server/api/profile/me.put.ts')).toContain('gender_identity')
    expect(read('server/api/profile/me.put.ts')).toContain('sexual_orientation')
    expect(read('docs/migrations/20260730_add_gender_identity.sql')).toContain('profiles_gender_identity_check')
    expect(read('server/api/profile/me.put.ts')).toContain('profiles_display_name_unique')
    expect(read('docs/migrations/20260729_unique_profile_names.sql')).toContain('lower(trim(display_name))')
    expect(read('server/api/onboarding/complete.post.ts')).toContain('Please finish every onboarding step')
  })
})
