import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, it, expect } from 'vitest'
import { readPage } from './pageTestUtils'

describe('core page contracts', () => {
  it('contact page keeps metadata title and support email link', () => {
    const source = readPage('contact.vue')
    expect(source).toContain("title: 'Contact · Lonely Radish'")
    expect(source).toContain('mailto:contact@lonelyradish.app')
  })

  it('privacy notice page keeps metadata title and heading copy', () => {
    const source = readPage('privacy-notice.vue')
    expect(source).toContain("title: 'Privacy Notice · Lonely Radish'")
    expect(source).toContain('Privacy Notice')
    expect(source).toContain('Last updated:')
  })

  it('home page keeps SEO metadata and activity-date call to action', () => {
    const source = readPage('index.vue')
    expect(source).toContain("title: 'Meet through activities you both want to do'")
    expect(source).toContain('Start matching')
    expect(source).toContain("navigateTo('/activities')")
    expect(source).toContain('to="/matches"')
    expect(source).toContain('New activity matches are ready to browse.')
    expect(source).toContain('Skip the endless swiping. Say yes to a plan.')
    expect(source).toContain('text-[#2A1520] sm:text-6xl')
    expect(source).toContain('user.value?.firstName')
    expect(source).toContain('user.value?.firstName')
    expect(source).toContain("'Welcome to Lonely Radish'")
  })

  it('mock activity and match pages are routed separately from the preview page', () => {
    const activities = readPage('activities/index.vue')
    const activityMatches = readPage('activities/[slug].vue')
    const profile = readPage('profiles/[slug].vue')
    const plan = readPage('plans/[slug].vue')
    const matches = readPage('matches/index.vue')
    const nav = readFileSync(resolve(process.cwd(), 'components/BlankNavBar.vue'), 'utf8')

    expect(activities).toContain("title: 'Date Ideas · Lonely Radish'")
    expect(activities).toContain('Browse people through broader interests.')
    expect(activities).toContain("slug: 'sports'")
    expect(activities).toContain("slug: 'games'")
    expect(activities).toContain("`/activities/${category.slug}`")
    expect(activities).toContain('Browse people')
    expect(activityMatches).toContain("visiblePeople.length === 1 ? 'person' : 'people'")
    expect(activityMatches).toContain('broader category')
    expect(activityMatches).toContain('No one is browsing in this category yet')
    expect(activityMatches).toContain('`/profiles/${person.slug}`')
    expect(activityMatches).toContain('`/api/activities/${slug.value}/people`')
    expect(profile).toContain("`${profile.value.name}'s Profile · Lonely Radish`")
    expect(profile).toContain('About me')
    expect(profile).toContain('Activities I’d enjoy together')
    expect(profile).toContain('/images/maya-profile-triptych.png')
    expect(profile).toContain('/images/nina-profile-triptych.png')
    expect(profile).toContain('/images/alex-profile-triptych.png')
    expect(profile).toContain('/images/maya-profile-triptych-2.png')
    expect(profile).toContain('galleryPhotos')
    expect(profile).toContain('.slice(0, 6)')
    expect(profile).toContain("pronouns: 'they/them'")
    expect(profile).toContain("'Show interest'")
    expect(profile).toContain('Already matched with ${profile.name}')
    expect(profile).toContain('Unmatched from ${profile.name}')
    expect(profile).toContain('useDailyInterest()')
    expect(activityMatches).toContain('useDailyInterest()')
    expect(matches).toContain("title: 'Matches & Plans · Lonely Radish'")
    expect(matches).toContain('Turn mutual interest into a real date.')
    expect(matches).toContain("title: 'New matches'")
    expect(matches).toContain("title: 'Planning'")
    expect(matches).toContain("title: 'Confirmed dates'")
    expect(matches).toContain('`/profiles/${match.slug}`')
    expect(matches).toContain('View {{ match.name }}’s profile')
    expect(plan).toContain('Plan a date with {{ personName }}')
    expect(plan).toContain('Suggest up to three times')
    expect(plan).toContain('Enter a public venue')
    expect(plan).toContain('Keep logistics simple')
    expect(plan).toContain('Add preset')
    expect(plan).toContain('removeQuickMessage')
    expect(plan).toContain('lonely-radish-planning-quick-messages')
    expect(plan).toContain('interestsByPerson')
    expect(plan).toContain('Add a short invite note')
    expect(plan).toContain('inviteMessageLimit = 240')
    expect(nav).toContain("to: '/activities'")
    expect(nav).toContain("to: '/matches'")
    expect(nav).toContain("label: 'Discover date ideas'")
    expect(nav).toContain("label: 'Matches & plans'")
  })
})
