import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, it, expect } from 'vitest'
import { readPage } from './pageTestUtils'

describe('core page contracts', () => {
  it('contact page keeps metadata title and support email link', () => {
    const source = readPage('contact.vue')
    expect(source).toContain("title: 'Contact · Lonely Radish'")
    expect(source).toContain('mailto:contact@lonelyradish.app')
  })

  it('privacy notice page keeps metadata title and heading copy', () => {
    const source = readPage('privacy-notice.vue')
    expect(source).toContain("title: 'Privacy Notice · Lonely Radish'")
    expect(source).toContain('Privacy Notice')
    expect(source).toContain('Last updated:')
  })

  it('home page keeps SEO metadata and activity-date call to action', () => {
    const source = readPage('index.vue')
    expect(source).toContain("title: 'Meet through activities you both want to do'")
    expect(source).toContain('Start matching')
    expect(source).toContain("navigateTo('/activities')")
    expect(source).toContain('to="/matches"')
    expect(source).toContain('New activity matches are ready to browse.')
    expect(source).toContain('Skip the endless swiping. Say yes to a plan.')
    expect(source).toContain('text-[#2A1520] sm:text-6xl')
    expect(source).toContain('user.value?.firstName')
    expect(source).toContain('user.value?.firstName')
    expect(source).toContain("'Welcome to Lonely Radish'")
  })

  it('mock activity and match pages are routed separately from the preview page', () => {
    const activities = readPage('activities/index.vue')
    const activityMatches = readPage('activities/[slug].vue')
    const profile = readPage('profiles/[slug].vue')
    const plan = readPage('plans/[slug].vue')
    const matches = readPage('matches/index.vue')
    const nav = readFileSync(resolve(process.cwd(), 'components/BlankNavBar.vue'), 'utf8')

    expect(activities).toContain("title: 'Date Ideas · Lonely Radish'")
    expect(activities).toContain('Browse people through broader interests.')
    expect(activities).toContain("slug: 'sports'")
    expect(activities).toContain("slug: 'games'")
    expect(activities).toContain("`/activities/${category.slug}`")
    expect(activities).toContain('Browse people')
    expect(activityMatches).toContain("visiblePeople.length === 1 ? 'person' : 'people'")
    expect(activityMatches).toContain('broader category')
    expect(activityMatches).toContain('No one is browsing in this category yet')
    expect(activityMatches).toContain('`/profiles/${person.slug}`')
    expect(activityMatches).toContain('`/api/activities/${slug.value}/people`')
    expect(profile).toContain("`${profile.value.name}'s Profile · Lonely Radish`")
    expect(profile).toContain('About me')
    expect(profile).toContain('Activities I’d enjoy together')
    expect(profile).toContain('/images/maya-profile-triptych.png')
    expect(profile).toContain('/images/nina-profile-triptych.png')
    expect(profile).toContain('/images/alex-profile-triptych.png')
    expect(profile).toContain('/images/maya-profile-triptych-2.png')
    expect(profile).toContain('galleryPhotos')
    expect(profile).toContain('.slice(0, 6)')
    expect(profile).toContain("pronouns: 'they/them'")
    expect(profile).toContain("'Show interest'")
    expect(profile).toContain('Already matched with ${profile.name}')
    expect(profile).toContain('Unmatched from ${profile.name}')
    expect(profile).toContain("activitiesFlipped && 'is-flipped'")
    expect(profile).toContain(`profile.relationshipStatus !== 'unmatched'`)
    expect(profile).toContain('Past connection')
    expect(profile).toContain("route.query.connection !== 'past'")
    expect(profile).toContain("profile.contactDetails && profile.isMatched && profile.relationshipStatus !== 'unmatched'")
    expect(profile).toContain('profileInterests')
    expect(profile).toContain('.profile-flip-card:hover')
    expect(profile).toContain('useDailyInterest()')
    expect(activityMatches).toContain('useDailyInterest()')
    expect(matches).toContain("title: 'Matches & Plans · Lonely Radish'")
    expect(matches).toContain('Turn mutual interest into a real date.')
    expect(matches).toContain("title: 'New matches'")
    expect(matches).toContain("title: 'Planning'")
    expect(matches).toContain("title: 'Confirmed dates'")
    expect(matches).toContain('`/profiles/${match.slug}`')
    expect(matches).toContain('View {{ match.name }}’s profile')
    expect(plan).toContain('Plan a date with {{ personName }}')
    expect(plan).toContain('Suggest up to three times')
    expect(plan).toContain('Enter a public venue')
    expect(plan).toContain('Keep logistics simple')
    expect(plan).toContain('Add preset')
    expect(plan).toContain('removeQuickMessage')
    expect(plan).toContain('lonely-radish-planning-quick-messages')
    expect(plan).toContain('interestsByPerson')
    expect(plan).toContain('Add a short invite note')
    expect(plan).toContain('inviteMessageLimit = 240')
    expect(nav).toContain("to: '/activities'")
    expect(nav).toContain("to: '/matches'")
    expect(nav).toContain("label: 'Discover date ideas'")
    expect(nav).toContain("label: 'Matches & plans'")
  })

  it('provides a private preview of the signed-in users real profile', () => {
    const preview = readPage('profile/preview.vue')
    const nav = readFileSync(resolve(process.cwd(), 'components/BlankNavBar.vue'), 'utf8')
    expect(preview).toContain("middleware: 'logged-in'")
    expect(preview).toContain("'/api/profile/me'")
    expect(preview).toContain('Contact details and private matching')
    expect(preview).toContain('preferences are never included')
    expect(preview).toContain('gallerySlots')
    expect(preview).toContain('class="mt-5 grid gap-5 lg:grid-cols-2"')
    expect(preview).toContain('Activities I’d enjoy together')
    expect(preview).toContain("activitiesFlipped && 'is-flipped'")
    expect(preview).toContain('My broader interests')
    expect(preview).toContain('.flip-card:hover')
    expect(preview).toContain('prefers-reduced-motion: reduce')
    expect(preview).toContain('Preview only — these controls are not active here.')
    expect(preview).toContain('Report profile')
    expect(preview).toContain('visible only to active matches')
    expect(preview).not.toContain('People see your selected interests when they discover you')
    expect(nav).toContain('to="/profile/preview"')
    expect(readFileSync(resolve(process.cwd(), 'server/api/profile/me.get.ts'), 'utf8')).toContain('activities: activities.rows.map')
    expect(readFileSync(resolve(process.cwd(), 'server/api/profile/me.get.ts'), 'utf8')).toContain('interestCategories:')
  })
})
