import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('received interests', () => {
  it('shows persisted incoming interests without blocked profiles', () => {
    const api = read('server/api/interests/received.get.ts')
    expect(api).toContain('di.recipient_id=$1')
    expect(api).toContain('di.resolved_at is null')
    expect(api).toContain('di.inbox_bypassed=false')
    expect(api).toContain('order by di.created_at asc limit 5')
    expect(api).toContain('pendingInterestCount')
    expect(api).toContain('not exists(select 1 from blocks')
    expect(api).toContain('di.created_at<=ended.ended_at')
    expect(read('server/api/matches/index.get.ts')).toContain('interest_inbox_state')
    expect(read('pages/interests/received.vue')).toContain('Accept and match')
    expect(read('pages/interests/received.vue')).toContain('Pass')
    expect(read('pages/interests/received.vue')).toContain('Pending interests stay open for 14 days')
    expect(read('pages/interests/received.vue')).toContain('Recently closed')
    expect(read('pages/faq.vue')).toContain('Why can I receive only five interests at a time?')
  })
  it('allows the recipient to deliberately create a match', () => {
    const repository = read('server/repositories/matches.ts')
    const service = read('server/services/matches/MatchService.ts')
    expect(repository).toContain('di.recipient_id=$2')
    expect(repository).toContain('insert into matches')
    expect(service).toContain("'new_match'")
    expect(service).toContain('active match limit')
    expect(read('pages/interests/received.vue')).toContain('activeMatchLimit')
  })
  it('paces incoming interests while allowing reciprocal choices to match directly', () => {
    const migration = read('docs/migrations/20260901_pace_received_interests.sql')
    const capacityMigration = read('docs/migrations/20260905_optimize_discovery_interest_capacity.sql')
    const service = read('server/services/interests/InterestService.ts')
    const repository = read('server/repositories/interests.ts')
    const discovery = read('server/utils/discoveryFilters.ts')
    expect(migration).toContain('interest_inbox_reopens_at')
    expect(migration).toContain("resolution in ('accepted','passed','expired')")
    expect(service.indexOf('hasReverseInterest')).toBeLessThan(service.indexOf('recipientInboxAcceptingInterests'))
    expect(service).toContain("throw conflict('This person is not accepting new interests right now')")
    expect(repository).toContain('and inbox.pending_count<5 for update of inbox')
    expect(repository).toContain('resolvePairInterestsAccepted')
    expect(discovery).toContain('recipientInterestAvailabilityWhere')
    expect(discovery).toContain('reciprocal.sender_id=p.user_id')
    expect(discovery).toContain('coalesce(inbox_state.pending_count,0)<5')
    expect(discovery).not.toContain('select count(*) from daily_interests pending_interest')
    expect(capacityMigration).toContain('daily_interests_maintain_pending_count')
    expect(capacityMigration).toContain('users_create_interest_inbox_state')
    expect(capacityMigration).toContain('reconcile_pending_interest_counts')
    expect(capacityMigration).toContain("constraint='interest_inbox_capacity'")
  })
})
