import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('received interests', () => {
  it('shows persisted incoming interests without blocked profiles', () => {
    const api = read('server/api/interests/received.get.ts')
    expect(api).toContain('di.recipient_id=$1')
    expect(api).toContain('di.resolved_at is null')
    expect(api).toContain('di.inbox_bypassed=false')
    expect(api).toContain('order by di.created_at asc limit 5')
    expect(api).toContain('pendingInterestCount')
    expect(api).toContain('not exists(select 1 from blocks')
    expect(api).toContain('di.created_at<=ended.ended_at')
    expect(read('server/api/matches/index.get.ts')).toContain('di.created_at<=ended.ended_at')
    expect(read('pages/interests/received.vue')).toContain('Accept and match')
    expect(read('pages/interests/received.vue')).toContain('Pass')
    expect(read('pages/interests/received.vue')).toContain('Passing is final')
    expect(read('pages/interests/received.vue')).toContain('does not reveal a replacement straight away')
    expect(read('pages/faq.vue')).toContain('Why can I receive only five interests at a time?')
  })
  it('allows the recipient to deliberately create a match', () => {
    const repository = read('server/repositories/matches.ts')
    const service = read('server/services/matches/MatchService.ts')
    expect(repository).toContain('di.recipient_id=$2')
    expect(repository).toContain('insert into matches')
    expect(service).toContain("'new_match'")
    expect(service).toContain('active match limit')
    expect(read('pages/interests/received.vue')).toContain('activeMatchLimit')
  })
  it('paces incoming interests while allowing reciprocal choices to match directly', () => {
    const migration = read('docs/migrations/20260901_pace_received_interests.sql')
    const service = read('server/services/interests/InterestService.ts')
    const repository = read('server/repositories/interests.ts')
    const discovery = read('server/utils/discoveryFilters.ts')
    expect(migration).toContain('interest_inbox_reopens_at')
    expect(migration).toContain("resolution in ('accepted','passed','expired')")
    expect(service.indexOf('hasReverseInterest')).toBeLessThan(service.indexOf('recipientInboxAcceptingInterests'))
    expect(service).toContain("throw conflict('This person is not accepting new interests right now')")
    expect(repository).toContain('and resolved_at is null and inbox_bypassed=false)<5')
    expect(repository).toContain('resolvePairInterestsAccepted')
    expect(discovery).toContain('recipientInterestAvailabilityWhere')
    expect(discovery).toContain('reciprocal.sender_id=p.user_id')
  })
})
