import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('received interests', () => {
  it('shows persisted incoming interests without blocked profiles', () => {
    const api = read('server/api/interests/received.get.ts')
    expect(api).toContain('di.recipient_id=$1')
    expect(api).toContain('di.resolved_at is null')
    expect(api).toContain('di.inbox_bypassed=false')
    expect(api).toContain('order by di.created_at asc limit 5')
    expect(api).toContain('pendingInterestCount')
    expect(api).toContain('not exists(select 1 from blocks')
    expect(api).toContain('di.created_at<=ended.ended_at')
    expect(read('server/api/matches/index.get.ts')).toContain('interest_inbox_state')
    expect(read('pages/interests/received.vue')).toContain('Accept and match')
    expect(read('pages/interests/received.vue')).toContain('Not for me')
    expect(read('pages/interests/received.vue')).toContain('stays here for up to 14 days')
    expect(read('pages/interests/received.vue')).toContain('Earlier interest')
    expect(api).toContain('row_number() over(partition by di.sender_id')
    expect(api).toContain('di.sender_rank=1')
    expect(api).toContain('pending.resolved_at is null')
    expect(api).toContain('as "reconnectRequest"')
    expect(read('pages/interests/received.vue')).toContain('Reconnect request expired')
    expect(read('pages/interests/received.vue')).toContain('took back their reconnect request')
    expect(api).toContain('reconnect_note.message as "reconnectNote"')
    expect(api).toContain('matched.ended_by=di.sender_id')
    expect(read('pages/interests/received.vue')).toContain('Reconnect request</span>')
    expect(read('pages/interests/received.vue')).toContain('Accept and reconnect')
    expect(read('pages/interests/received.vue')).toContain('Do not reconnect')
    expect(read('pages/interests/received.vue')).toContain('person.reconnectNote')
    expect(read('pages/faq.vue')).toContain('Why can I see only five interests at a time?')
  })
  it('allows the recipient to deliberately create a match', () => {
    const repository = read('server/repositories/matches.ts')
    const service = read('server/services/matches/MatchService.ts')
    expect(repository).toContain('di.recipient_id=$2')
    expect(repository).toContain('insert into matches')
    expect(service).toContain("'new_match'")
    expect(service).toContain('active match limit')
    expect(read('pages/interests/received.vue')).toContain('activeMatchLimit')
    expect(repository).toContain("notification.kind='interest_received'")
  })
  it('queues incoming interests while showing the oldest five at a time', () => {
    const queueMigration = read('docs/migrations/20260918_queue_received_interests.sql')
    const service = read('server/services/interests/InterestService.ts')
    const repository = read('server/repositories/interests.ts')
    const discovery = read('server/utils/discoveryFilters.ts')
    expect(service).not.toContain('recipientInboxAcceptingInterests')
    expect(service).not.toContain('not accepting new interests right now')
    expect(repository).not.toContain('pending_count<5')
    expect(repository).toContain('resolvePairInterestsAccepted')
    expect(discovery).toContain('recipientInterestAvailabilitySelect')
    expect(discovery).toContain('true as "acceptingInterest"')
    const profileApi = read('server/api/profiles/[slug].get.ts')
    const profilePage = read('pages/profiles/[slug].vue')
    expect(profileApi).toContain('true as "acceptingInterest"')
    expect(profilePage).not.toContain('profile.acceptingInterest === false')
    expect(profilePage).not.toContain('currently considering five interests')
    expect(discovery).not.toContain('select count(*) from daily_interests pending_interest')
    expect(queueMigration).toContain('pending_count=pending_count+1')
    expect(queueMigration).not.toContain('pending_count<5')
    expect(read('server/api/interests/received.get.ts')).toContain('order by di.created_at asc limit 5')
    expect(read('pages/interests/received.vue')).toContain('The next interest appears when you accept or pass on someone.')
  })
})
