begin;

alter table users add column if not exists deletion_requested_at timestamptz;
alter table users add column if not exists deletion_status text;
alter table users add column if not exists deleted_at timestamptz;

create table if not exists billing_subscriptions (
  stripe_subscription_id text primary key,
  user_id text not null references users(id) on delete cascade,
  stripe_customer_id text not null,
  plan text not null check (plan in ('monthly', 'yearly')),
  subscription_status text not null,
  cancel_at_period_end boolean not null default false,
  current_period_start timestamptz,
  current_period_end timestamptz,
  canceled_at timestamptz,
  latest_invoice_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists billing_subscriptions_user_idx on billing_subscriptions(user_id);

create table if not exists stripe_events (
  event_id text primary key,
  event_type text not null,
  stripe_created_at timestamptz not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  status text not null default 'received' check (status in ('received', 'processing', 'processed', 'failed', 'ignored')),
  payload jsonb not null,
  stripe_subscription_id text,
  stripe_customer_id text,
  user_id text,
  error_message text
);
create index if not exists stripe_events_user_received_idx on stripe_events(user_id,received_at desc);
create index if not exists stripe_events_subscription_idx on stripe_events(stripe_subscription_id);

create table if not exists account_deletion_jobs (
  id bigint generated by default as identity primary key,
  user_id text not null,
  status text not null default 'pending' check (status in ('pending','processing','failed','completed')),
  attempt_count integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);
create index if not exists account_deletion_jobs_user_idx on account_deletion_jobs(user_id,created_at desc);

do $$ begin
  alter table billing_subscriptions enable row level security;
  alter table stripe_events enable row level security;
  alter table account_deletion_jobs enable row level security;
  revoke all on billing_subscriptions,stripe_events,account_deletion_jobs from anon,authenticated;
exception when undefined_object then null;
end $$;

commit;
