begin;

create extension if not exists pgcrypto;

create table if not exists users (
  id text primary key,
  email text not null,
  first_name text,
  last_name text,
  role text not null default 'member' check (role in ('member', 'moderator', 'admin')),
  account_status text not null default 'active' check (account_status in ('active', 'paused', 'suspended', 'deleting')),
  timezone text not null default 'Europe/London',
  stripe_customer_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleting_at timestamptz
);

alter table users add column if not exists first_name text;
alter table users add column if not exists last_name text;
alter table users add column if not exists role text not null default 'member';
alter table users add column if not exists account_status text not null default 'active';
alter table users add column if not exists timezone text not null default 'Europe/London';
alter table users add column if not exists updated_at timestamptz not null default now();

create unique index if not exists users_email_lower_unique on users (lower(email));

create table if not exists entitlements (
  user_id text primary key references users(id) on delete cascade,
  plan text not null default 'free' check (plan in ('free', 'monthly', 'yearly')),
  subscription_status text not null default 'no_subscription',
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  canceled_at timestamptz
);

create table if not exists profiles (
  user_id text primary key references users(id) on delete cascade,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  display_name text not null check (char_length(display_name) between 1 and 80),
  date_of_birth date,
  pronouns text check (pronouns is null or char_length(pronouns) <= 40),
  bio text check (bio is null or char_length(bio) <= 1000),
  neighbourhood text check (neighbourhood is null or char_length(neighbourhood) <= 100),
  latitude numeric(9,6),
  longitude numeric(9,6),
  visibility text not null default 'active' check (visibility in ('draft', 'active', 'paused')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists profile_photos (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references users(id) on delete cascade,
  storage_key text,
  public_url text not null check (char_length(public_url) <= 2000),
  alt_text text check (alt_text is null or char_length(alt_text) <= 200),
  position smallint not null check (position between 1 and 6),
  created_at timestamptz not null default now(),
  unique (user_id, position),
  check (storage_key is null or char_length(storage_key) <= 500)
);

create table if not exists activities (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 100),
  category text not null check (char_length(category) between 1 and 60),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index if not exists activities_name_lower_unique on activities (lower(name));

create table if not exists profile_activities (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references users(id) on delete cascade,
  activity_id bigint references activities(id) on delete cascade,
  custom_label text,
  position smallint not null check (position between 1 and 10),
  created_at timestamptz not null default now(),
  unique (user_id, position),
  check ((activity_id is not null) <> (custom_label is not null)),
  check (custom_label is null or char_length(custom_label) between 1 and 100)
);
create unique index if not exists profile_activities_catalog_unique on profile_activities(user_id, activity_id) where activity_id is not null;
create unique index if not exists profile_activities_custom_unique on profile_activities(user_id, lower(custom_label)) where custom_label is not null;

create table if not exists match_preferences (
  user_id text primary key references users(id) on delete cascade,
  max_distance_km smallint not null default 10 check (max_distance_km between 1 and 500),
  minimum_age smallint not null default 18 check (minimum_age between 18 and 100),
  maximum_age smallint not null default 80 check (maximum_age between 18 and 100),
  timing text[] not null default '{}',
  public_places_only boolean not null default true,
  interested_genders text[] not null default '{}',
  open_to_everyone boolean not null default true,
  preferred_ethnicities text[] not null default '{}',
  no_ethnicity_preference boolean not null default true,
  updated_at timestamptz not null default now(),
  check (minimum_age <= maximum_age),
  check (cardinality(timing) <= 10),
  check (cardinality(interested_genders) <= 10),
  check (cardinality(preferred_ethnicities) <= 20)
);

create table if not exists availability (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references users(id) on delete cascade,
  label text not null check (char_length(label) between 1 and 100),
  position smallint not null check (position between 1 and 10),
  unique (user_id, position)
);

create table if not exists daily_interests (
  id uuid primary key default gen_random_uuid(),
  sender_id text not null references users(id) on delete cascade,
  recipient_id text not null references users(id) on delete cascade,
  sender_day date not null,
  created_at timestamptz not null default now(),
  unique (sender_id, sender_day),
  check (sender_id <> recipient_id)
);
create index if not exists daily_interests_recipient_idx on daily_interests(recipient_id, created_at desc);

create table if not exists matches (
  id uuid primary key default gen_random_uuid(),
  user_one_id text not null references users(id) on delete cascade,
  user_two_id text not null references users(id) on delete cascade,
  status text not null default 'active' check (status in ('active', 'unmatched', 'blocked')),
  matched_at timestamptz not null default now(),
  unique (user_one_id, user_two_id),
  check (user_one_id < user_two_id)
);
create index if not exists matches_user_two_idx on matches(user_two_id, matched_at desc);

create table if not exists date_proposals (
  id uuid primary key default gen_random_uuid(),
  match_id uuid references matches(id) on delete cascade,
  inviter_id text not null references users(id) on delete cascade,
  invitee_id text not null references users(id) on delete cascade,
  activity_label text not null check (char_length(activity_label) between 1 and 100),
  invite_note text check (invite_note is null or char_length(invite_note) <= 240),
  venue text not null check (char_length(venue) between 1 and 200),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (inviter_id <> invitee_id)
);
create index if not exists date_proposals_invitee_idx on date_proposals(invitee_id, created_at desc);

create table if not exists proposal_times (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid not null references date_proposals(id) on delete cascade,
  proposed_at timestamptz not null,
  position smallint not null check (position between 1 and 3),
  unique (proposal_id, position),
  unique (proposal_id, proposed_at)
);

create table if not exists blocks (
  blocker_id text not null references users(id) on delete cascade,
  blocked_id text not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id text not null references users(id) on delete cascade,
  reported_id text not null references users(id) on delete cascade,
  category text not null check (category in ('spam', 'harassment', 'safety', 'impersonation', 'other')),
  details text check (details is null or char_length(details) <= 2000),
  status text not null default 'open' check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  check (reporter_id <> reported_id)
);

create or replace function set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists profiles_set_updated_at on profiles;
create trigger profiles_set_updated_at before update on profiles for each row execute function set_updated_at();
drop trigger if exists match_preferences_set_updated_at on match_preferences;
create trigger match_preferences_set_updated_at before update on match_preferences for each row execute function set_updated_at();
drop trigger if exists date_proposals_set_updated_at on date_proposals;
create trigger date_proposals_set_updated_at before update on date_proposals for each row execute function set_updated_at();

do $$ declare table_name text; begin
  foreach table_name in array array['users','entitlements','profiles','profile_photos','activities','profile_activities','match_preferences','availability','daily_interests','matches','date_proposals','proposal_times','blocks','reports']
  loop
    execute format('alter table %I enable row level security', table_name);
    execute format('revoke all on table %I from anon, authenticated', table_name);
  end loop;
exception when undefined_object then null;
end $$;

commit;
